import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { loadFile, findProjectFile, findProjectRoot } from "./memory.js";
import { MemoryFile } from "./format.js";

export type EmitFormat = "agents" | "claude" | "cursorrules" | "windsurfrules" | "geminimd" | "continuerules" | "copilot";

interface FormatSpec {
  id: EmitFormat;
  fileName: string;
  displayName: string;
  tool: string;
}

export const FORMATS: Record<EmitFormat, FormatSpec> = {
  agents: { id: "agents", fileName: "AGENTS.md", displayName: "AGENTS.md", tool: "OpenAI Codex / Aider / cross-tool standard" },
  claude: { id: "claude", fileName: "CLAUDE.md", displayName: "CLAUDE.md", tool: "Claude Code" },
  cursorrules: { id: "cursorrules", fileName: ".cursorrules", displayName: ".cursorrules", tool: "Cursor" },
  windsurfrules: { id: "windsurfrules", fileName: ".windsurfrules", displayName: ".windsurfrules", tool: "Windsurf" },
  geminimd: { id: "geminimd", fileName: "GEMINI.md", displayName: "GEMINI.md", tool: "Gemini CLI" },
  continuerules: { id: "continuerules", fileName: ".continuerules", displayName: ".continuerules", tool: "Continue.dev" },
  copilot: { id: "copilot", fileName: ".github/copilot-instructions.md", displayName: "copilot-instructions.md", tool: "VS Code Copilot" },
};

const HEADER_BANNER_PREFIX = "<!-- Generated by MemoryBridge from .ai-memory.md.";
const HEADER_BANNER_SUFFIX = "Edit the source (.ai-memory.md), not this file. -->";

function headerBanner(contentHash: string): string {
  return `${HEADER_BANNER_PREFIX} hash=${contentHash}. ${HEADER_BANNER_SUFFIX}`;
}

function contentHash(text: string): string {
  return crypto.createHash("sha1").update(text).digest("hex").slice(0, 12);
}

function extractHash(existingText: string): string | null {
  const m = existingText.match(/hash=([a-f0-9]{12})/);
  return m ? m[1] : null;
}

function joinLines(arr: string[]): string {
  return arr.join("\n");
}

function renderMarkdownStyle(file: MemoryFile, title: string): string {
  const out: string[] = [];
  out.push(`# ${title}`);
  out.push("");

  const header = file.sections.get("@header") ?? [];
  if (header.length > 0) {
    out.push("## Project");
    out.push("");
    for (const l of header) {
      out.push(l.startsWith("- ") ? l : `- ${l}`);
    }
    out.push("");
  }

  const renderSection = (sectionName: string, heading: string) => {
    const lines = file.sections.get(sectionName);
    if (!lines || lines.length === 0) return;
    out.push(`## ${heading}`);
    out.push("");
    for (const l of lines) {
      const cleaned = l.replace(/^-\s*\[\d{4}-\d{2}-\d{2}\]\s*/, "- ");
      out.push(cleaned.startsWith("- ") ? cleaned : `- ${cleaned}`);
    }
    out.push("");
  };

  renderSection("@preferences", "Preferences");
  renderSection("@decisions", "Architectural Decisions");
  renderSection("@map", "File Map");
  renderSection("@issues", "Known Issues");
  renderSection("@env", "Environment");

  return joinLines(out);
}

function renderRulesStyle(file: MemoryFile): string {
  const out: string[] = [];
  out.push("# Rules generated by MemoryBridge — edit .ai-memory.md instead.");
  out.push("");

  const header = file.sections.get("@header") ?? [];
  for (const l of header) {
    out.push(`# ${l.replace(/^-\s*/, "")}`);
  }
  out.push("");

  const renderSection = (sectionName: string, heading: string) => {
    const lines = file.sections.get(sectionName);
    if (!lines || lines.length === 0) return;
    out.push(`## ${heading}`);
    for (const l of lines) {
      const cleaned = l.replace(/^-\s*\[\d{4}-\d{2}-\d{2}\]\s*/, "- ");
      out.push(cleaned.startsWith("- ") ? cleaned : `- ${cleaned}`);
    }
    out.push("");
  };

  renderSection("@preferences", "Preferences");
  renderSection("@decisions", "Decisions");
  renderSection("@map", "File map");
  renderSection("@issues", "Known issues");
  renderSection("@env", "Environment");

  return joinLines(out);
}

export function render(format: EmitFormat, file: MemoryFile): string {
  switch (format) {
    case "agents":
      return renderMarkdownStyle(file, "AGENTS.md — Project Instructions");
    case "claude":
      return renderMarkdownStyle(file, "Claude Code Instructions");
    case "geminimd":
      return renderMarkdownStyle(file, "Gemini Instructions");
    case "copilot":
      return renderMarkdownStyle(file, "Copilot Instructions");
    case "cursorrules":
    case "windsurfrules":
    case "continuerules":
      return renderRulesStyle(file);
  }
}

export interface EmitResult {
  format: EmitFormat;
  fileName: string;
  absPath: string;
  action: "created" | "updated" | "unchanged" | "would-create" | "would-update";
  bytes: number;
}

export function emit(format: EmitFormat, opts: { cwd?: string; dryRun?: boolean; force?: boolean } = {}): EmitResult | { error: string } {
  const cwd = opts.cwd ?? process.cwd();
  const memPath = findProjectFile(cwd);
  if (!memPath) return { error: "no .ai-memory.md found. Run `memorybridge add` first to create one." };

  const file = loadFile(memPath);
  const body = render(format, file);
  const newHash = contentHash(body);
  const text = `${headerBanner(newHash)}\n\n${body}`;
  const projectRoot = findProjectRoot(cwd);
  const spec = FORMATS[format];
  const target = path.join(projectRoot, spec.fileName);

  const existed = fs.existsSync(target);
  const existing = existed ? fs.readFileSync(target, "utf8") : "";

  if (existing === text) {
    return { format, fileName: spec.fileName, absPath: target, action: "unchanged", bytes: Buffer.byteLength(text, "utf8") };
  }

  if (existed) {
    if (!existing.startsWith(HEADER_BANNER_PREFIX)) {
      return { error: `refusing to overwrite ${spec.fileName}: file exists and was not created by MemoryBridge. Move or delete the file first, or pass --force.` };
    }
    if (!opts.force) {
      const recordedHash = extractHash(existing);
      if (recordedHash) {
        const existingBody = existing.replace(/^<!--[^>]*-->\n+/, "");
        const actualHash = contentHash(existingBody);
        if (recordedHash !== actualHash) {
          return { error: `refusing to overwrite ${spec.fileName}: file has been edited since MemoryBridge last wrote it (banner hash mismatch). Either copy your edits into .ai-memory.md, delete the file, or pass --force to overwrite.` };
        }
      }
    }
  }

  if (opts.dryRun) {
    return {
      format,
      fileName: spec.fileName,
      absPath: target,
      action: existed ? "would-update" : "would-create",
      bytes: Buffer.byteLength(text, "utf8"),
    };
  }

  const dir = path.dirname(target);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(target, text, "utf8");
  return {
    format,
    fileName: spec.fileName,
    absPath: target,
    action: existed ? "updated" : "created",
    bytes: Buffer.byteLength(text, "utf8"),
  };
}

export function emitAll(opts: { cwd?: string; only?: EmitFormat[]; dryRun?: boolean; force?: boolean } = {}): (EmitResult | { error: string; format: EmitFormat })[] {
  const formats: EmitFormat[] = opts.only ?? (Object.keys(FORMATS) as EmitFormat[]);
  const out: (EmitResult | { error: string; format: EmitFormat })[] = [];
  for (const f of formats) {
    const r = emit(f, { cwd: opts.cwd, dryRun: opts.dryRun, force: opts.force });
    if ("error" in r) out.push({ format: f, error: r.error });
    else out.push(r);
  }
  return out;
}

export function formatEmitReport(results: (EmitResult | { error: string; format: EmitFormat })[]): string {
  const out: string[] = [];
  out.push("");
  out.push("=== MemoryBridge Emit ===");
  out.push("");
  for (const r of results) {
    const spec = FORMATS[r.format];
    if ("error" in r) {
      out.push(`  [!] ${spec.displayName.padEnd(28)} ${r.error}`);
    } else {
      const verb = r.action.padEnd(13);
      const marker = r.action === "unchanged" ? "=" : r.action.startsWith("would-") ? "?" : "✓";
      out.push(`  [${marker}] ${spec.displayName.padEnd(28)} ${verb}  ${r.bytes.toString().padStart(5)} bytes  ${r.absPath}`);
    }
  }
  out.push("");
  return out.join("\n");
}
